services:
    heyform:
        image: heyform/community-edition:latest
        depends_on:
            - mongo
            - keydb
        environment:
            TZ: "Europe/Berlin"
            APP_HOMEPAGE_URL: "https://${DOMAIN}"
            SESSION_KEY: ${SESSION_KEY}
            FORM_ENCRYPTION_KEY: ${FORM_ENCRYPTION_KEY}
            MONGO_URI: "mongodb://mongo:27017/heyform"
            REDIS_HOST: keydb
            REDIS_PORT: 6379
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_SECURE: ${SMTP_SECURE}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            SMTP_FROM: ${SMTP_FROM}
        volumes:
            - uploads_volume:/app/static/upload
        labels:
            caddy_0: ${DOMAIN}
            caddy_0.reverse_proxy: "{{upstreams 9157}}"
            caddy_0.encode: zstd gzip
        restart: unless-stopped
        networks:
            - default
            - main-proxy

    mongo:
        image: percona/percona-server-mongodb:4.4
        environment:
            TZ: "Europe/Berlin"
        volumes:
            - db_volume:/data/db
        restart: unless-stopped

    keydb:
        image: eqalpha/keydb:6.3.3
        command: keydb-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru
        environment:
            TZ: "Europe/Berlin"
        volumes:
            - redis_volume:/data
        mem_limit: 256m
        restart: unless-stopped

volumes:
    db_volume:
    redis_volume:
    uploads_volume:

networks:
    main-proxy:
        external: true
